#!/bin/sh

#
# Email notification when an error log is output
#


#=================================================================#
# variable
#=================================================================#

SOURSE='/tmp/test/a'
TARGET='/tmp/test/b'

RESULT=`diff ${SOURSE} ${TARGET} | grep -E '^<' | perl -pe 's/^<\s//g'`
SUBJECT=`diff ${SOURSE} ${TARGET} | grep -E '^<' | perl -pe 's/^<\s//g' | head -n 1`
TO_ADDR='k.ishida@mail.hisashi.work'



#=================================================================#
# main
#=================================================================#

#echo '' | mail -s $SUBJECT $TO_ADDR


if [ -n "${RESULT}" ]; then
     echo "${RESULT}" | mail -s "${SUBJECT}" "${TO_ADDR}"
fi


cp ${SOURSE} ${TARGET}

exit 0
